name: create coverage badge(with PR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Create pull request
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: "Generated Coverage Badge"
          commit-message: "Generated Coverage Badge"
          delete-branch: true

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
